/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.DoctorDirectory;


/**
 *
 * @author asawari
 */
public class LookforDoctor extends javax.swing.JPanel {

    /**
     * Creates new form LookforDoctor
     */
    DoctorDirectory doctorDirectory;
   
    public LookforDoctor(DoctorDirectory doctorDirectory) {
        initComponents();
        
        ComboCommunity.addItem("MALDEN");
        ComboCommunity.addItem("HUNTINGTON");
        ComboCommunity.setSelectedItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctorDirectory = new javax.swing.JLabel();
        lblCommunity = new javax.swing.JLabel();
        lblDocName = new javax.swing.JLabel();
        lblHospName = new javax.swing.JLabel();
        ComboCommunity = new javax.swing.JComboBox<>();
        ComboHospital = new javax.swing.JComboBox<>();
        ComboDoctorName = new javax.swing.JComboBox<>();

        lblDoctorDirectory.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblDoctorDirectory.setText("Doctory Directory");

        lblCommunity.setText("Community");

        lblDocName.setText("Doctor Name:");

        lblHospName.setText("Hospital Name:");

        ComboCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Community"}));
        ComboCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboCommunityActionPerformed(evt);
            }
        });

        ComboHospital.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Hospital"}));

        ComboDoctorName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select Doctor"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(lblDoctorDirectory))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDocName)
                            .addComponent(lblCommunity)
                            .addComponent(lblHospName))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ComboCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblDoctorDirectory)
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommunity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHospName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocName)
                    .addComponent(ComboDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(330, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboCommunityActionPerformed
        
        if(ComboCommunity.getSelectedItem().equals("HUNTINGTON")){
            ComboHospital.removeAllItems();
            ComboHospital.setSelectedItem(null);
            ComboHospital.addItem("Massachusetts General Hospital");
            ComboHospital.addItem("Boston Medical Center");
            
        }
        else 
        if(ComboCommunity.getSelectedItem().equals("MALDEN")){
                
            ComboHospital.removeAllItems();
            ComboHospital.setSelectedItem(null);
            ComboHospital.addItem("Malden Hospital");
            ComboHospital.addItem("Malden General Hospital");  
 
        }
        
        if(ComboHospital.getSelectedItem().equals("Massachusetts General Hospital")){
            ComboDoctorName.removeAllItems();
            ComboDoctorName.addItem("Dr.Alex");
            ComboDoctorName.addItem("Dr.Matthew");
            ComboDoctorName.addItem("Dr.John");   
        }
        
        if(ComboHospital.getSelectedItem().equals("Boston Medical Center")){
            ComboDoctorName.removeAllItems();
            ComboDoctorName.addItem("Dr.Verma");
            ComboDoctorName.addItem("Dr.Andrew");
            ComboDoctorName.addItem("Dr.Mike");   
        }
        
        if(ComboHospital.getSelectedItem().equals("Malden Hospital")){
            ComboDoctorName.removeAllItems();
            ComboDoctorName.addItem("Dr.Nicholas");
            ComboDoctorName.addItem("Dr.Nisha");
            ComboDoctorName.addItem("Dr.Emma");   
        }
        
        if(ComboHospital.getSelectedItem().equals("Malden General Hospital")){
            ComboDoctorName.removeAllItems();
            ComboDoctorName.addItem("Dr.Olivia");
            ComboDoctorName.addItem("Dr.Andrew");
            ComboDoctorName.addItem("Dr.Charlotte");   
        }
        
    }//GEN-LAST:event_ComboCommunityActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboCommunity;
    private javax.swing.JComboBox<String> ComboDoctorName;
    private javax.swing.JComboBox<String> ComboHospital;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblDocName;
    private javax.swing.JLabel lblDoctorDirectory;
    private javax.swing.JLabel lblHospName;
    // End of variables declaration//GEN-END:variables
}
